name = "92lottery-dev"
compatibility_date = "2024-01-01"

[build]
command = "npm install --legacy-peer-deps && npm run build"

[env]
NODE_VERSION = "18.17.0"

[site]
bucket = ".next"

[pages]
pages_build_output_dir = ".next"
