[build]
command = "./cloudflare-build.sh"
output = ".next"

[build.environment]
NODE_VERSION = "18.17.1"
NPM_VERSION = "9.6.7"

[site]
bucket = ".next"
entry-point = "."

[[redirects]]
from = "/*"
to = "/index.html"
status = 200