[build]
command = "npm install --legacy-peer-deps && npm run build"
output = ".next"

[build.environment]
NODE_VERSION = "18.17.0"

[site]
bucket = ".next"

[functions]
directory = ".next/server/pages" 